### ISSUE TITLE
Why CORS blocking to execute AuthenticationEntryPoint class?

### ISSUE THREAD

**Issue by ghost** [codesandnotes/restsecurity#1]
Could you please guide us on http://stackoverflow.com/questions/32725249/cors-filter-issue-for-authentrypoint?

**Comment by codesandnotes** [comment]
Hi there! 

Believe it or not I don't have an account on StackOverflow, so I'm going to offer my help here :-)

I don't have the whole context, and I have not done pure MVC for a long time, but I'm quite certain that you're tackling two problems at once: the CORS filter and the authentication through Spring Security. 

Having banged my head more than once on these sort of problems, I would suggest you to proceed like this: 

1) Start by removing the CORS filter completely. 
2) Solve the authentication aspect first. With CORS disabled, you could test by typing some GET request directly in the browser, or use some add-on on Firefox such as "REST Easy" or "RESTClient". 
3) When that is sorted out, put back the CORS filter, but comment out everything in the class: just pass the request and response objects through. This is to make sure that the filter is not blocking the response for some reason (I'd doubt it, but who knows!). 
4) Finally, uncomment the code in your CORS filter. 

This should help you find out where the system is misbehaving, or help you understand what is missing. 

Additionally, feel free to checkout and download my two other GitHub repos: **secure-rest-angular-tut** and **secure-rest-spring-tut**. 

They are a fully-working implementation of a CORS+CSRF+Authentication-protected server (albeit using Java Configuration instead of XML) with a full client (albeit an AngularJS one). Maybe that will help you finding the missing piece? 

Hope this will help!

**Comment by ghost** [comment]
The fact that now if I kept CORS filter in web.xml file, and OPTIONS related security filters in XML file I can get login into the application and for wrong/incorrect credentials also it's working fine (but it bypassing AuthenticationEntryPoint - which is bad). But I developed code in  AuthenticationEntryPoint which checks whether user exists and it has failure attempts or not before allowing to execute anything for authentication,

CORS is blocking that authentication filter to execute. Please help me why? It should first execute  AuthenticationEntryPoint and then only go for authentication as per "entry-point-ref" of security.xml

`<http
    use-expressions="true" auto-config="false" create-session="stateless"
    disable-url-rewriting="true" entry-point-ref="entryPoint"
    authentication-manager-ref="authenticationManager">

<bean id="entryPoint" class="com.tcs.web.EntryPoint" />`

**Comment by ghost** [comment]
What entry is missing is spring security file, for invalid credentials it's not calling Authentication entry point where I am counting users failure attempts. Please please help me ..
